apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-app
  labels:
    app: angular-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-app
  template:
    metadata:
      labels:
        app: angular-app
    spec:
      containers:
      - name: angular-app
        image: nagasatishdocker/angular-crud-app:latest
        ports:
        - containerPort: 80
        resources:
            limits:
              cpu: 500m
            requests:
               cpu: 100m
