apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: angular-client
    app.kubernetes.io/instance: angular-client
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: front-end
    app.kubernetes.io/managed-by: kubectl
  name: angular-client
spec:
  selector:
    app: angular-client
  type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 80