apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: angular-client
    app.kubernetes.io/instance: angular-client
    app.kubernetes.io/version: '1.0.0'
    app.kubernetes.io/managed-by: kubectl
  name: angular-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-client
  template:
    metadata:
      labels:
        app: angular-client
    spec:
      containers:
        - image: 188691447767.dkr.ecr.ap-south-1.amazonaws.com/angular-java:latest
          imagePullPolicy: Always
          name: angular-client
          ports:
            - containerPort: 80